# Generated by Django 5.0.7 on 2024-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="body",
            new_name="content",
        ),
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
