# Generated by Django 5.0.7 on 2024-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="permalink",
            field=models.SlugField(blank=True, default="", max_length=255),
        ),
    ]
