# Generated by Django 5.0.7 on 2024-08-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="permalink",
            field=models.SlugField(default="", max_length=255, unique=True),
        ),
    ]
