# Generated by Django 5.0.7 on 2024-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0002_article_permalink"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="seo_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="article",
            name="seo_title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
