# Generated by Django 5.0.7 on 2024-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0002_alter_article_permalink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="permalink",
            field=models.SlugField(default="", max_length=255, null=True),
        ),
    ]
