# Generated by Django 5.0.7 on 2024-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kb", "0003_alter_article_permalink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website_title",
                    models.CharField(blank=True, default="openKB", max_length=255),
                ),
                (
                    "website_description",
                    models.TextField(
                        blank=True,
                        default="openKB is an Open Source Node.js Markdown based knowledge base/FAQ/Wiki app.",
                    ),
                ),
                ("show_website_logo", models.BooleanField(default=True)),
                (
                    "website_context_base_url",
                    models.URLField(
                        blank=True, default="http://127.0.0.1:4444/openkb/"
                    ),
                ),
                ("allow_api_access", models.BooleanField(default=False)),
                ("api_access_token", models.CharField(blank=True, max_length=255)),
                ("password_protect", models.BooleanField(default=False)),
                ("index_article_body", models.BooleanField(default=False)),
                ("select_theme", models.CharField(blank=True, max_length=255)),
                (
                    "select_language",
                    models.CharField(
                        choices=[("en", "English")], default="en", max_length=10
                    ),
                ),
                ("show_logon_link", models.BooleanField(default=True)),
                (
                    "date_format",
                    models.CharField(default="DD/MM/YYYY h:mmA", max_length=50),
                ),
                ("article_suggestions_allowed", models.BooleanField(default=True)),
                ("google_analytics_code", models.TextField(blank=True)),
            ],
        ),
    ]
