# Generated by Django 5.0.7 on 2024-08-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0004_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_voting",
                    models.BooleanField(default=True, verbose_name="Allow voting"),
                ),
                (
                    "show_article_meta",
                    models.BooleanField(
                        default=True, verbose_name="Show article meta data"
                    ),
                ),
                (
                    "show_author_email",
                    models.BooleanField(default=True, verbose_name="Show author email"),
                ),
                (
                    "article_links_open_new_page",
                    models.BooleanField(
                        default=True, verbose_name="Article links open new page"
                    ),
                ),
                (
                    "add_header_anchors",
                    models.BooleanField(
                        default=False, verbose_name="Add header anchors"
                    ),
                ),
                (
                    "enable_editor_spellchecker",
                    models.BooleanField(
                        default=True, verbose_name="Enable editor spellchecker"
                    ),
                ),
                (
                    "allow_article_versioning",
                    models.BooleanField(
                        default=False, verbose_name="Allow article versioning"
                    ),
                ),
                (
                    "allow_mermaid",
                    models.BooleanField(default=False, verbose_name="Allow Mermaid"),
                ),
                (
                    "allow_mathjax",
                    models.BooleanField(default=False, verbose_name="Allow MathJax"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisplaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_top_articles", models.IntegerField(default=10)),
                ("show_published_date", models.BooleanField(default=True)),
                ("show_view_count", models.BooleanField(default=True)),
                (
                    "update_view_count_when_logged_in",
                    models.BooleanField(default=False),
                ),
                ("show_featured_articles", models.BooleanField(default=True)),
                (
                    "show_featured_articles_when_viewing_article",
                    models.BooleanField(default=False),
                ),
                ("featured_article_count", models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name="StyleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_background_color", models.CharField(blank=True, max_length=7)),
                ("header_text_color", models.CharField(blank=True, max_length=7)),
                ("footer_background_color", models.CharField(blank=True, max_length=7)),
                ("footer_text_color", models.CharField(blank=True, max_length=7)),
                ("button_background_color", models.CharField(blank=True, max_length=7)),
                ("button_text_color", models.CharField(blank=True, max_length=7)),
                ("link_color", models.CharField(blank=True, max_length=7)),
                ("page_text_color", models.CharField(blank=True, max_length=7)),
                ("page_font", models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
