# Generated by Django 5.0.7 on 2024-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0005_articlesettings_displaysettings_stylesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
