# Generated by Django 5.0.7 on 2024-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0006_article_featured"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Settings",
            new_name="WebsiteSettings",
        ),
        migrations.AlterField(
            model_name="displaysettings",
            name="update_view_count_when_logged_in",
            field=models.BooleanField(default=True),
        ),
    ]
