# Generated by Django 5.0.7 on 2024-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kb", "0007_rename_settings_websitesettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylesettings",
            name="button_background_color",
            field=models.CharField(blank=True, default="#007bff", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="button_text_color",
            field=models.CharField(blank=True, default="#7a3838", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="footer_background_color",
            field=models.CharField(blank=True, default="#343a40", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="footer_text_color",
            field=models.CharField(blank=True, default="#ffffff", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="header_background_color",
            field=models.CharField(blank=True, default="#2D3E50", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="header_text_color",
            field=models.CharField(blank=True, default="#FFFFFF", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="link_color",
            field=models.CharField(blank=True, default="#0f000c", max_length=7),
        ),
        migrations.AlterField(
            model_name="stylesettings",
            name="page_text_color",
            field=models.CharField(blank=True, default="#212529", max_length=7),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="date_format",
            field=models.CharField(default="d/m/Y H:iA", max_length=50),
        ),
        migrations.AlterField(
            model_name="websitesettings",
            name="website_description",
            field=models.TextField(
                blank=True,
                default="openKB is an Open Source Django Markdown based knowledge base/FAQ/Wiki app.",
            ),
        ),
    ]
